#BleeposExploitFixes v1.8


#ChunkBan Patch
chunkbanpatch: true #Should we patch chunk bans?

#Dupe Patches
entitythoughportal: true #Should we let entities with chests through portals?

#Lever Spam Patch
leverspampatch: true #Should we patch lever spam?
leverspam: 3 #How many times per second can a player spam a lever
message: '&6Please dont spam levers!' #Message we should send when a player spams a lever (applies for kick)
leverspamkick: true #Should we kick players for spamming levers?

#Lag Patches
purgewitherskulls: true #Should we purge wither skulls?