#BleeposExploitFixes v2.1

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Patches
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

leverspam:
  enabled: true #Should we patch lever spam?
  interval: 3 #How many times per second can a player spam a lever
  message: '&6Please dont spam levers!' #Message we should send when a player spams a lever (applies for kick)
  kick: true #Should we kick players for spamming levers?

liquidlag:
  enabled: true #Should we stop liquid from flowing at a certain tps?
  disabletps: 15 #Tps to stop liquid from flowing at

elytra:
  enabled: true #Limit Elytra Speed?
  speed: 5 #Speed to limit at (Default 50 BPS)
  kick: true #Kick the player for going too fast?
  message: '&6You are going too fast!' #Message to send to player if they are going too fast
  disabledattps: true #Disable elytras at certain tps?
  tps: 17 #Tps to disable at
  lowtpsmessage: '&6The tps is too low todo that!'

explosions:
  disabled: false #Should we disable TNT?
  disableattps: true #Should we disable tnt at a certain tps?
  tps: 16 #Tps to disable tnt at

preventnetherroof: true #Should we prevent players from entering the nether roof?
endgatewaycrash: true #Should we fix the End Gateway Crash?
multipledragons: true #Should we fix multiple ender dragons?
dispenserpatch: true #Should we fix the dispenser crash?
chunkbanpatch: true #Should we patch chunk bans?
entitythoughportal: true #Should we let entities with chests through portals?
purgewitherskulls: true #Should we purge wither skulls?
minecartcrash: true #Should we prevent the minecart crash?


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Commands
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

kill:
  enabled: true
  message: '&cGoodbye cruel world...'

help:
  enabled: true
  help:
      - '&6-----------------------------------------------------'
      - '&3/ignore <name> to ignore a player.'
      - '&3/ignorelist to list ignored players.'
      - '&3/r <message> to reply to the last person that messaged you.'
      - '&3/l <message> to message the last person that you messaged.'
      - '&3/w <name> <message> OR /msg <name> <message> to pm a player.'
      - '&3/vote to vote'
      - '&3/kill to kill yourself.'
      - '&6-----------------------------------------------------'

say:
  enabled: true
  prefix: '&6[&bBleeposExploitFixer&6] {message}'


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Join Messages
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

firstjoin:
  enabled: true
  message: "&7{player} Joined for the first time."

join:
  enabled: true
  message: "&7{player} joined."

leave:
  enabled: true
  message: "&7{player left.}"