#BleeposExploitFixes v1.9


#ChunkBan Patch
chunkbanpatch: true #Should we patch chunk bans?

#Dupe Patches
entitythoughportal: true #Should we let entities with chests through portals?
itemframedupe: true #Should we patch the item frame dupe?
kickmessage: '&6 Please dont try to item frame dupe!' #Item Frame Dupe kick message

#Lever Spam Patch
leverspampatch: true #Should we patch lever spam?
leverspam: 3 #How many times per second can a player spam a lever
message: '&6Please dont spam levers!' #Message we should send when a player spams a lever (applies for kick)
leverspamkick: true #Should we kick players for spamming levers?

#Lag Patches
purgewitherskulls: true #Should we purge wither skulls?

#Exploit Patches
endgatewaycrash: true #Should we fix the End Gateway Crash?
multipledragons: true #Should we fix multiple ender dragons?
dispenserpatch: true #Should we fix the dispenser crash?