name: BleeposExploitFixer
version: 2.1
main: dev.bleepo.bleeposexploitfixer.Main
depend: [ProtocolLib]
authors: [ Bleepo ]
description: Exploit Fixer
commands:
  kill:
    description: Kill yourself
    usage: /<command>

  help:
    description: Get Help
    usage: /<command>

  say:
    description: Say something to the entire server
    usage: /<command> <message>

  befreload:
    description: Reload the plugin
    usage: /<command>